# Generated by Django 4.1 on 2023-09-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default='trip_packages/main_images/default-trip-img.jpg', null=True, upload_to='trip_packages/main_images/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(db_index=True)),
                ('duration', models.IntegerField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('season', models.JSONField(db_index=True)),
                ('max_group_size', models.IntegerField(db_index=True)),
                ('overall_rating', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True)),
                ('difficulty', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_packages/additional_images/')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trip_packages.trips')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_group_size', models.IntegerField()),
                ('booked_slots', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='trip_packages.trips')),
            ],
        ),
    ]
