# Generated by Django 4.1 on 2023-10-29 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import trip_packages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default='trip_packages/main_images/default-trip-img.jpg', null=True, upload_to='trip_packages/main_images/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(db_index=True)),
                ('duration', models.IntegerField(db_index=True)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('season', models.JSONField(db_index=True)),
                ('max_group_size', models.IntegerField(db_index=True)),
                ('overall_rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Challenging'), (4, 'Hard')], db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_packages/additional_images/')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trip_packages.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=trip_packages.models.review_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trip_packages.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_group_size', models.IntegerField()),
                ('booked_slots', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='trip_packages.trips')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='trip_packages.trips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trip')},
            },
        ),
    ]
