# Generated by Django 4.1 on 2023-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=models.ImageField(upload_to='trip_packages/additional_images/'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
    ]
