# Generated by Django 4.1 on 2023-10-29 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_overview', models.TextField()),
                ('included', models.TextField()),
                ('not_included', models.TextField()),
                ('equipment_list', models.TextField()),
                ('skill_level', models.TextField()),
                ('weather_conditions', models.TextField()),
                ('cancellation_policy', models.TextField()),
                ('important_notes', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='trip_packages.trips')),
            ],
        ),
    ]
