# Generated by Django 4.1 on 2023-11-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
