# Generated by Django 4.1 on 2023-11-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0002_alter_reviews_comment_alter_reviews_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
