# Generated by Django 4.1 on 2023-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0002_alter_tripimage_image_alter_trips_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='main_image',
            field=models.ImageField(blank=True, default='trip_packages/main_images/default-trip-img.jpg', null=True, upload_to='trip_packages/main_images/'),
        ),
    ]
