# Generated by Django 4.1 on 2025-08-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_packages', '0003_delete_tripimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name_plural': 'Trips'},
        ),
    ]
